pipeline {
    agent any

    environment {
        // 🔹 Replace this with your Firebase Project ID (found in Firebase console)
        FIREBASE_PROJECT_ID = 'personal-portfolio-site'

        // 🔹 Add this credential in Jenkins (Manage Jenkins → Credentials → Secret Text)
        //    Use the Firebase CI token generated by `firebase login:ci`
        FIREBASE_TOKEN = credentials('firebase-token')

        // 🔹 The branch that will trigger automatic deployment
        DEPLOY_BRANCH = 'main'
    }

    stages {

        stage('Checkout') {
            steps {
                echo '📦 Fetching latest code from GitHub repository...'
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                echo '📦 Installing Node.js dependencies...'
                // Change to 'sh' if Jenkins runs on Linux
                bat 'npm install'
            }
        }

        stage('Build Project') {
            steps {
                echo '⚙️ Building portfolio project...'
                // Change to 'sh' if Jenkins runs on Linux
                bat 'npm run build'
            }
        }

        stage('Deploy to Firebase Hosting') {
            when {
                branch "${env.DEPLOY_BRANCH}"
            }
            steps {
                echo "🚀 Deploying project to Firebase Hosting..."
                // Change to 'sh' if Jenkins runs on Linux
                bat """
                npx firebase deploy --project %FIREBASE_PROJECT_ID% --token %FIREBASE_TOKEN%
                """
            }
        }
    }

    post {
        success {
            echo '✅ Deployment completed successfully!'
        }
        failure {
            echo '❌ Deployment failed. Check build logs for details.'
        }
    }
}
